---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ibm-blockchain-network.name" . }}-org1peer1
  labels:
    app: {{ template "ibm-blockchain-network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "ibm-blockchain-network.name" . }}-org1peer1
      labels:
        app: {{ template "ibm-blockchain-network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        name: {{ template "ibm-blockchain-network.name" . }}-org1peer1
    spec:
      volumes:
      - name: {{ template "ibm-blockchain-shared.name" . }}-pvc
        persistentVolumeClaim:
         claimName: {{ template "ibm-blockchain-shared.name" . }}-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      initContainers:
      - name: init-service
        image: busybox:1.28.4
        command:
        - sh
        - -c
        - |
          while [ ! -f /shared/bootstrapped ]; do
            echo Waiting for bootstrap
            sleep 5s
          done
        volumeMounts:
        - mountPath: /shared
          name: {{ template "ibm-blockchain-shared.name" . }}-pvc
      containers:
      - name: org1peer1
        image: {{ .Values.fabric.peerImage }}
        imagePullPolicy: {{ .Values.fabric.pullPolicy }}
        command:
          - sh
          - -c
          - |
            touch /shared/status_org1peer1_complete &&
            peer node start --peer-defaultchain=false
        env:
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ADDRESS
          value: {{ template "ibm-blockchain-network.name" . }}-org1peer1:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: {{ template "ibm-blockchain-network.name" . }}-org1peer1:30110
        - name: CORE_PEER_GOSSIP_ORGLEADER	
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE	
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        # - name: CORE_PEER_DISCOVERY_PERIOD
        #   value: 60s
        # - name: CORE_PEER_DISCOVERY_TOUCHPERIOD
        #   value: 60s
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_LOGGING_CAUTHDSL
          value: debug
        - name: CORE_LOGGING_GOSSIP
          value: debug
        - name: CORE_LOGGING_LEDGER
          value: debug
        - name: CORE_LOGGING_MSP
          value: debug
        - name: CORE_LOGGING_POLICIES
          value: debug
        - name: CORE_LOGGING_GRPC
          value: debug
        - name: CORE_PEER_ID
          value: org1peer1
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: goleveldb
        # - name: PEER_CFG_PATH
        #   value: peer_config/
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: {{ template "ibm-blockchain-network.name" . }}-orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: {{ template "ibm-blockchain-shared.name" . }}-pvc
        - mountPath: /host/var/run/docker.sock
          name: dockersocket

