---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-cc-instantiate
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cc-instantiate
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc

  containers:
  - name: chaincode-instantiate
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command:
    - sh
    - -c
    - |
      while [ ! -f /shared/status_chaincode_install_org1peer1_complete ] || [ ! -f /shared/status_chaincode_install_org2peer1_complete ]; do
        echo Waiting for Chaincode installs on org1peer1 and org2peer1 to complete
        sleep 5s
      done
      
      peer chaincode instantiate \
      --orderer ${ORDERER_URL} \
      --channelID ${CHANNEL_NAME} \
      --name ${CHAINCODE_NAME} \
      --version ${CHAINCODE_VERSION} \
      --ctor '{"Args":["init","a","100","b","200"]}'

      rm /shared/status_chaincode_install_org1peer1_complete &&
      rm /shared/status_chaincode_install_org2peer1_complete &&
      touch /shared/status_chaincode_instantiate_complete
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: CHAINCODE_NAME
      value: {{ .Values.chaincode.name }}
    - name: CHAINCODE_VERSION
      value: {{ .Values.chaincode.version }}
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_ADDRESS
      value: {{ template "network.name" . }}-org1peer1:30110
    - name: ORDERER_URL
      value: {{ template "network.name" . }}-orderer:31010
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc