---
apiVersion: v1
kind: Pod
metadata:
  name: chaincodeinstall-org1peer1
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "ibm-blockchain-shared.name" . }}-pvc
    persistentVolumeClaim:
      claimName: {{ template "ibm-blockchain-shared.name" . }}-pvc
  containers:
  - name: chaincodeinstall
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command:
    - sh
    - -c
    - |
      while [ ! -f /shared/status_joinchannel_org1peer1_complete ]; do
        echo Waiting for org1peer1 to join
        sleep 5s
      done
      
      git clone -b v1.0.3 https://github.com/hyperledger/fabric $GOPATH/src/github.com/hyperledger/fabric/
      
      peer chaincode install \
      --name ${CHAINCODE_NAME} \
      --version ${CHAINCODE_VERSION} \
      --path github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/

      touch /shared/status_chaincode_install_org1peer1_complete &&
      rm /shared/status_joinchannel_org1peer1_complete
    env:
    - name: CHAINCODE_NAME
      value: {{ .Values.chaincode.name }}
    - name: CHAINCODE_VERSION
      value: {{ .Values.chaincode.version }}
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_ADDRESS
      value: {{ template "ibm-blockchain-network.name" . }}-org1peer1:30110
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "ibm-blockchain-shared.name" . }}-pvc
