---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "network.name" . }}-composer-playground
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-composer-playground
      labels:
        app: {{ template "network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ template "network.name" . }}-composer-playground
    spec:
      volumes:
      - name: {{ template "shared.name" . }}-pvc
        persistentVolumeClaim:
          claimName: {{ template "shared.name" . }}-pvc
      - name: {{ template "composer.name" . }}-pvc
        persistentVolumeClaim:
          claimName: {{ template "composer.name" . }}-pvc
      initContainers:
      - name: init-service
        image: busybox:1.28.4
        command:
        - sh
        - -c
        - |
          while [ ! -f /shared/status_composer_card_import_complete ]; do
            echo Waiting for Composer card import to complete
            sleep 5s
          done
          echo Composer card import completed
        volumeMounts:
        - name: {{ template "shared.name" . }}-pvc
          mountPath: /shared
        - name: {{ template "composer.name" . }}-pvc
          mountPath: /home/composer/.composer
      containers:
      - name: composer-playground
        image: {{ .Values.composer.playgroundImage }}
        imagePullPolicy: {{ .Values.composer.pullPolicy }}
        volumeMounts:
        - name: {{ template "composer.name" . }}-pvc
          mountPath: /home/composer/.composer
...
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "network.name" . }}-composer-playground
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  type: NodePort
  selector:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
    role: {{ template "network.name" . }}-composer-playground
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31080
    name: http
...