---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "network.name" . }}-composer-rest-server
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-composer-rest-server
      labels:
        app: {{ template "network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}  
        role: composer-rest-server
    spec:
      volumes:
      - name: {{ template "network.name" . }}-composer-pvc
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-composer-pvc
      containers:
      - name: composer-rest-server
        image: {{ .Values.composer.restServerImage }}
        imagePullPolicy: {{ .Values.composer.pullPolicy }}
        env:
        - name: COMPOSER_CARD
          value: {{ .Values.composer.card }}
        - name: COMPOSER_NAMESPACES
          value: never
        volumeMounts:
        - name: {{ template "network.name" . }}-composer-pvc
          mountPath: /home/composer/.composer
...
---
# The service to expose composer rest server
apiVersion: v1
kind: Service
metadata:
  name: {{ template "network.name" . }}-composer-rest-server
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  type: NodePort
  selector:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
    role: composer-rest-server
  ports:
  - protocol: TCP
    port: 3000
    #nodePort: 31090
    name: http
...