---
apiVersion: v1
kind: Pod
metadata:
  name: createchannel
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: {{ template "ibm-blockchain-shared.name" . }}-pvc
  containers:
  - name: createchanneltx
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command:
    - sh
    - -c
    - |
      cd /shared
      pwd
      ls
      more /shared/configtx.yaml
      configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME}
      touch /shared/status_channeltx_complete
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: FABRIC_CFG_PATH
      value: /shared
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: shared

  - name: createchannel
    image: {{ .Values.blockchain.peerImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command: 
    - sh
    - -c
    - |
      while [ ! -f /shared/status_channeltx_complete ]
      do
        echo Waiting for channeltx
        sleep 5s
      done
      peer channel create --orderer ${ORDERER_URL} --channelID ${CHANNEL_NAME} --file /shared/${CHANNEL_NAME}.tx
      rm /shared/status_channeltx_complete
      touch /shared/status_channelcreate_complete
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: ORDERER_URL
      value: {{ template "ibm-blockchain-network.name" . }}-orderer:31010
    - name: CORE_PEER_ADDRESSAUTODETECT
      value: "false"
    - name: CORE_PEER_NETWORKID
      value: nid1
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
    - name: CORE_LOGGING_LEVEL
      value: debug
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: shared
