---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "network.name" . }}-debug
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-debug
      labels:
        app: {{ template "network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: debug
    spec:
      volumes:
      - name: {{ template "network.name" . }}-shared-pvc
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-shared-pvc
      - name: {{ template "network.name" . }}-composer-pvc
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-composer-pvc
      containers:
      - name: debug
        image: busybox:1.28.4
        command: 
        - sh
        - -c
        - |
          while true; do
            sleep 15s
          done
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /shared
          name: {{ template "network.name" . }}-shared-pvc
        - mountPath: /home/composer/.composer
          name: {{ template "network.name" . }}-composer-pvc
