---
kind: Pod
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-debug-nfs
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: debug-nfs
spec:
  restartPolicy: Never
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  - name: {{ template "network.name" . }}-composer-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-composer-pvc
  containers:
  - name: debug
    image: busybox:1.28.4
    imagePullPolicy: IfNotPresent
    command: 
    - sh
    - -c
    - |
      while true; do
        sleep 15s
      done
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
    - mountPath: /home/composer/.composer
      name: {{ template "network.name" . }}-composer-pvc
