---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "network.name" . }}-nfs
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
...
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "network.name" . }}-nfs
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-nfs
      labels:
        app: {{ template "network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: nfs
    spec:
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: {{ template "network.name" . }}-nfs
      volumes:
      - name: {{ template "network.name" . }}-nfs
        persistentVolumeClaim:
          claimName: {{ template "network.name" . }}-nfs
          readOnly: false
...
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "network.name" . }}-nfs
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
...