---
kind: Pod
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-org1peer1-debug-cli
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: debug-cli
spec:
  restartPolicy: Never
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  - name: {{ template "network.name" . }}-composer-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-composer-pvc
  containers:
  - name: cli
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command:
    - sh
    - -c
    - |
      while true; do sleep 15s; done
    env:
    - name: CHANNEL_NAME
      value: {{ .Values.channel.name }}
    - name: CHAINCODE_NAME
      value: {{ .Values.chaincode.name }}
    - name: CHAINCODE_VERSION
      value: {{ .Values.chaincode.version }}
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_ADDRESS
      value: {{ template "network.name" . }}-org1peer1:30110
    - name: ORDERER_URL
      value: {{ template "network.name" . }}-orderer:31010
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
    - mountPath: /home/composer/.composer
      name: {{ template "network.name" . }}-composer-pvc
