---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-org2peer1-cc-install
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: org2peer1-cc-install
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-shared-pvc
  containers:
  - name: chaincode-install
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command: 
    - sh
    - -c
    - |
      while [ ! -f /shared/status_joinchannel_org2peer1_complete ]; do
        echo Waiting for org2peer1 to join
        sleep 5s
      done

      git clone -b v1.0.3 https://github.com/hyperledger/fabric $GOPATH/src/github.com/hyperledger/fabric/
      
      peer chaincode install \
      --name ${CHAINCODE_NAME} \
      --version ${CHAINCODE_VERSION} \
      --path github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/

      touch /shared/status_chaincode_install_org2peer1_complete &&
      rm /shared/status_joinchannel_org2peer1_complete
    env:
    - name: CHAINCODE_NAME
      value: {{ .Values.chaincode.name }}
    - name: CHAINCODE_VERSION
      value: {{ .Values.chaincode.version }}
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org1MSP
    - name: CORE_PEER_ADDRESS
      value: {{ template "network.name" . }}-org1peer1:30210
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
