---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "network.name" . }}-org2peer1
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "network.name" . }}-org2peer1
      labels:
        app: {{ template "network.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: org2peer1
    spec:
      volumes:
      - name: {{ template "network.name" . }}-shared-pvc
        persistentVolumeClaim:
         claimName: {{ template "network.name" . }}-shared-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      initContainers:
      - name: init-service
        image: busybox:1.28.4
        command:
        - sh
        - -c
        - |
          while [ ! -f /shared/bootstrapped ]; do
            echo Waiting for bootstrap
            sleep 5s
          done
          echo bootstrap completed
        volumeMounts:
        - mountPath: /shared
          name: {{ template "network.name" . }}-shared-pvc
      containers:
      - name: org2peer1
        image: {{ .Values.fabric.peerImage }}
        imagePullPolicy: {{ .Values.fabric.pullPolicy }}
        command:
        - sh
        - -c
        - |
          touch /shared/status_org2peer1_complete &&
          peer node start --peer-defaultchain=false
        env:
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ADDRESS
          value: {{ template "network.name" . }}-org2peer1:30210
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30210
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30211
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: {{ template "network.name" . }}-org2peer1:30210
        - name: CORE_PEER_GOSSIP_ORGLEADER	
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE	
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        # - name: CORE_PEER_DISCOVERY_PERIOD
        #   value: 60s
        # - name: CORE_PEER_DISCOVERY_TOUCHPERIOD
        #   value: 60s
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: Org2MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_LOGGING_CAUTHDSL
          value: debug
        - name: CORE_LOGGING_GOSSIP
          value: debug
        - name: CORE_LOGGING_LEDGER
          value: debug
        - name: CORE_LOGGING_MSP
          value: debug
        - name: CORE_LOGGING_POLICIES
          value: debug
        - name: CORE_LOGGING_GRPC
          value: debug
        - name: CORE_PEER_ID
          value: org2peer1
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: goleveldb
        # - name: PEER_CFG_PATH
        #   value: peer_config/
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: {{ template "network.name" . }}-orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: {{ template "network.name" . }}-shared-pvc
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
...
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "network.name" . }}-org2peer1
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: org2peer1
  ports:
  - protocol: TCP
    port: 30210
    #nodePort: 30210
    targetPort: 30210
    name: grpc
  - protocol: TCP
    port: 30211
    #nodePort: 30211
    targetPort: 30211
    name: events
...