---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-shared-pv
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ template "network.name" . }}-nfs.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-shared-pvc
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  select:
    matchLabels:
      name: {{ template "network.name" . }}-shared-pv
...
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-composer-pv
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ template "network.name" . }}-nfs.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "network.name" . }}-composer-pvc
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  select:
    matchLabels:
      name: {{ template "network.name" . }}-shared-pv
...
