---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "shared.name" . }}-pv
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.service.name }}.{{ .Values.nfs.service.namespace }}.svc.cluster.local
    path: {{ .Values.nfs.path }}
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "shared.name" . }}-pvc
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  select:
    matchLabels:
      name: {{ template "shared.name" . }}-pv
...
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "composer.name" . }}-pv
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.service.name }}.{{ .Values.nfs.service.namespace }}.svc.cluster.local
    path: {{ .Values.nfs.path }}
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "composer.name" . }}-pvc
  labels:
    app: {{ template "network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  select:
    matchLabels:
      name: {{ template "composer.name" . }}-pv
...