---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "network.name" . }}-bootstrap
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  restartPolicy: Never
  volumes:
  - name: {{ template "network.name" . }}-shared-pvc
    persistentVolumeClaim:
     claimName: {{ template "network.name" . }}-shared-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  - name: {{ template "network.name" . }}-composer-pvc
    persistentVolumeClaim:
      claimName: {{ template "network.name" . }}-composer-pvc
  - name: config
    configMap:
      name: {{ template "network.name" . }}-configmap       
  containers:
  - name: cryptogen
    image: {{ .Values.fabric.toolsImage }}
    imagePullPolicy: {{ .Values.fabric.pullPolicy }}
    command:
    - sh
    - -c
    - -e
    - |
      cryptogen generate --config /configtx/crypto-config.yaml
      cp -r crypto-config /shared/

      for file in $(find /shared/ -iname *_sk); do
        dir=$(dirname $file); mv ${dir}/*_sk ${dir}/key.pem
      done

      find /shared -type d | xargs chmod a+rx
      find /shared -type f | xargs chmod a+r

      cat /configtx/configtx.yaml | sed --expression="s|blockchain-|${DEPLOYMENT_NAME}-|g" > /shared/configtx.yaml
      cd /shared/

      configtxgen -profile ComposerOrdererGenesis -outputBlock orderer.block

      find /shared -type d | xargs chmod a+rx
      find /shared -type f | xargs chmod a+r

      sleep 2s
      echo "Starting bootstrap"
      cp -r /configtx/cas /shared
      echo "Done copying"
      touch /shared/bootstrapped
      rm -f /shared/status_configtxgen_complete
      mkdir -p /home/composer/.composer
      chown 1000 /home/composer/.composer
      touch /shared/status_bootstrapping_complete
      echo "Done with bootstrapping"      
    env:
     - name: PEERHOST1
       value: {{ template "network.name" . }}-org1peer1
     - name: PEERPORT1
       value: "30110"
     - name: ORDERER_URL
       value: {{ template "network.name" . }}-orderer:31010
     - name: FABRIC_CFG_PATH
       value: /shared
     - name: DEPLOYMENT_NAME
       value: {{ template "network.name" . }}
    volumeMounts:
    - mountPath: /shared
      name: {{ template "network.name" . }}-shared-pvc
    - mountPath: /configtx
      name: config


